# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_geohash_wrappers", use_symbols = TRUE, package_name = "geohash")

#' @docType package
#' @usage NULL
#' @useDynLib geohash, .registration = TRUE
NULL

encode <- function(x, y, length) .Call(wrap__encode, x, y, length)

decode <- function(geohash) .Call(wrap__decode, geohash)

decode_bbox <- function(geohash, crs) .Call(wrap__decode_bbox, geohash, crs)

neighbor <- function(geohash, direction) .Call(wrap__neighbor, geohash, direction)

neighbors <- function(geohash) .Call(wrap__neighbors, geohash)


# nolint end
